import{S as h,i}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function g(o,r){const e=`https://pixabay.com/api/?key=45376910-43038ea3ca87cb1ac327a6384&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${r}`;try{const n=await(await fetch(e)).json();return console.log("API response data:",n),{images:n.hits||[],totalHits:n.totalHits||0}}catch(t){throw console.error("Error fetching images:",t),t}}let y;function p(o,r=!1){const s=document.querySelector(".gallery");if(r||(s.innerHTML=""),o.length===0){showNoImagesMessage();return}const a=o.map(w).join("");s.insertAdjacentHTML("beforeend",a),y?y.refresh():y=new h(".gallery a"),b()}function b(){const r=document.querySelector(".gallery").lastElementChild;if(!r)return;const s=r.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}function w({webformatURL:o,largeImageURL:r,tags:s,likes:a,views:e,comments:t,downloads:n}){return`
    <div class="image-card">
      <a href="${r}">
        <img src="${o}" alt="${s}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${a}</p>
        <p class="info-item"><b>Views:</b> ${e}</p>
        <p class="info-item"><b>Comments:</b> ${t}</p>
        <p class="info-item"><b>Downloads:</b> ${n}</p>
      </div>
    </div>
  `}const v=document.querySelector("#search-form"),L=document.querySelector("#search-input"),d=document.querySelector("#loader"),u=document.querySelector("#load-more-button");let f=1,m="",c=0,l=0;v.addEventListener("submit",async o=>{o.preventDefault();const r=L.value.trim();if(r===""){i.warning({title:"Warning",message:"Please enter a search query!"});return}m=r,f=1,l=0,d.style.display="block",u.style.display="none";try{const{images:s,totalHits:a}=await g(m,f);s&&a?(c=a,l+=s.length,p(s),l<c?u.style.display="block":l===c&&i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):i.warning({title:"Warning",message:"No images found. Please try a different search query."})}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{d.style.display="none"}});u.addEventListener("click",async()=>{f+=1,d.style.display="block";try{const{images:o}=await g(m,f);l+=o.length,p(o,!0),l>=c&&(u.style.display="none",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Failed to load more images. Please try again later."})}finally{d.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
